blog/urls.py
from django.urls import path

from blog.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
    profile
)

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),
    path('profile/', profile, name='profile'),
]

from django.conf import settings
from django.contrib.staticfiles import views
from django.urls import re_path

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]

blog/models.py
# import os
# import random

# from django.conf import settings
# from django.core.mail import send_mail
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField(default='<img src="/media/post_content_images/example.jpg" width="512" height="512" alt="Pipenv | Python">')
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text


class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django.forms import ModelForm, TextInput, Textarea

from blog.models import Comment, Reply



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Name',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Comment(comments will appear once approved.It should be approved within a year, so please be patient)',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '返信内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from blog.forms import CommentForm, ReplyForm
from blog.models import Post, Category, Tag, Comment, Reply


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 3


class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class SearchPostView(ListView):
    model = Post
    template_name = 'blog/search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))


class CommentFormView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)


class ReplyFormView(CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        reply.comment = get_object_or_404(Comment, pk=comment_pk)
        reply.save()
        return redirect('blog:post_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
        return context


@login_required
def reply_approve(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.approve()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)


@login_required
def reply_remove(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.delete()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)

def profile(request):
    return render(request, 'blog/profile.html')

def links(request):
    return render(request, 'blog/links.html')

blog/templates/blog/snippets/comments.html
{% for comment in post.comments.all %}
{% if user.is_authenticated or comment.approved %}
<div class="comment">
  <strong>{{ comment.author }}</strong>・{{ comment.timestamp }}
  <p>{{ comment.text|linebreaksbr }}</p>
  <p>
    <a href="{% url 'blog:reply_form' comment.pk %}">返信する</a>
    {% if not comment.approved %}
    ｜<a class="text-success" href="{% url 'blog:comment_approve' comment.pk %}">承認</a>
    ｜<a class="text-danger" href="{% url 'blog:comment_remove' comment.pk %}">削除</a>
    {% endif %}
  </p>

  {% for reply in comment.replies.all %}
  {% if user.is_authenticated or reply.approved %}
  <div class="reply ml-5">
    <strong>{{ reply.author }}</strong>・{{ reply.timestamp }}
    <p>{{ reply.text|linebreaksbr }}</p>
    <p>
      {% if not reply.approved %}
      <a class="text-success" href="{% url 'blog:reply_approve' reply.pk %}">承認</a>
      ｜<a class="text-danger" href="{% url 'blog:reply_remove' reply.pk %}">削除</a>
      {% endif %}
    </p>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endif %}
{% endfor %}

blog/templates/blog/snippets/main_post_list.html
{% for post in object_list %}
{% if user.is_authenticated or post.is_public %}

<div class="card mb-3">
  {% if post.image %}
  <a href="{% url 'blog:post_detail' post.id %}">
    <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
  </a>
  {% endif %}
  <div class="card-body">
    {% if not post.is_public %}
    <h5><span class="badge badge-secondary">下書き</span></h5>
    {% endif %}
    <a href="{% url 'blog:post_detail' post.id %}">
      <h5 class="card-title">{{ post.title }}</h5>
    </a>
    <p class="card-text">{{ post.published_at|date:"Y-m-d H:i:s" }}</p>
    <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">Read Articles</a>
  </div>
</div>

{% endif %}
{% empty %}
<p>No postings yet.</p>
{% endfor %}

blog/templates/blog/snippets/pagination.html
{% if is_paginated %}
<nav>
  {% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">前へ</a>
  {% endif %}

  {% for num in paginator.page_range %}
  {% if page_obj.number == num %}
  <span>{{ num }}</span>
  {% else %}
  <a href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a>
  {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}">次へ</a>
  {% endif %}
</nav>
{% endif %}

blog/templates/blog/snippets/pagination_b.html
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}

    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <a class="page-link">
        {{ num }}
        <span class="sr-only">(current)</span>
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

blog/templates/blog/snippets/search_form.html
<form class="form-inline my-2 my-lg-0" action="{% url 'blog:search_post' %}" method="GET">
  <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

blog/templates/blog/snippets/sidebar.html
<div class="card mb-3">
  <div class="card-header">
    Category
  </div>
  <ul class="list-group list-group-flush">
    {% for category in categories|dictsort:"id" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'blog:category_post' category.slug %}" class="card-link">{{ category.name }}</a>
      <span class="badge badge-primary badge-pill">{{ category.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
</div>

<div class="card">
  <div class="card-header">
    Tag
  </div>
  <ul class="list-group list-group-flush">
    {% for tag in tags|dictsortreversed:"num_posts"|slice:":5" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'blog:tag_post' tag.slug %}" class="card-link">{{ tag.name }}</a>
      <span class="badge badge-primary badge-pill">{{ tag.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
<!--  <div class="card-body text-center">-->
<!--    <a href="{% url 'blog:tag_list' %}" class="card-link">Watch All Tags</a>-->
<!--  </div>-->
</div>