blog/urls.py
from django.urls import path

from blog.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
    profile
)

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),
    path('profile/', profile, name='profile'),
]

from django.conf import settings
from django.contrib.staticfiles import views
from django.urls import re_path

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]

blog/models.py
# import os
# import random

# from django.conf import settings
# from django.core.mail import send_mail
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField(default='<img src="/media/post_content_images/example.jpg" width="512" height="512" alt="Pipenv | Python">')
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text


class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django.forms import ModelForm, TextInput, Textarea

from blog.models import Comment, Reply



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Name',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Comment(comments will appear once approved.It should be approved within a year, so please be patient)',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '返信内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from blog.forms import CommentForm, ReplyForm
from blog.models import Post, Category, Tag, Comment, Reply


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 3


class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class SearchPostView(ListView):
    model = Post
    template_name = 'blog/search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))


class CommentFormView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)


class ReplyFormView(CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        reply.comment = get_object_or_404(Comment, pk=comment_pk)
        reply.save()
        return redirect('blog:post_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
        return context


@login_required
def reply_approve(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.approve()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)


@login_required
def reply_remove(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.delete()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)

def profile(request):
    return render(request, 'blog/profile.html')

def links(request):
    return render(request, 'blog/links.html')

blog/templates/blog/calendar.html
<div class="calendar-section">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
        <th>土</th>
        <th>日</th>
      </tr>
    </thead>
    <tbody>
      {% for week in calendar %}
      <tr>
        {% for day in week %}
        <td>
          {% if day.posts %}
          <a href="{% url 'blog:posts_by_date' day.date.year day.date.month day.date.day %}">
            {{ day.date.day }}
          </a>
          {% else %}
          {{ day.date.day }}
          {% endif %}
        </td>
        {% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

blog/templates/blog/category_list.html
{% extends "base.html" %}

{% block title %}All Categories | {{ block.super }}{% endblock %}
{% block description %}All Categories{% endblock %}

{% block content %}
<div class="container mt-4">
  <h1 class="mb-4">All Categories</h1>
  <div class="list-group">
    {% for category in object_list %}
    <a href="{% url 'blog:category_post' category.slug %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
      {{ category.name }}
      <span class="badge badge-primary badge-pill">{{ category.num_posts }}</span>
    </a>
    {% empty %}
    <li class="list-group-item">No Categories</li>
    {% endfor %}
  </div>
</div>
{% endblock %}

blog/templates/blog/category_post.html
{% extends "base.html" %}

{% block title %}{{ category.name }} | {{ block.super }}{% endblock %}
{% block description %}[{{ category.name }}]'s{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4 text-uppercase font-weight-bold border-bottom pb-2">Category: {{ category.name }}</h1>
      <div class="main-posts bg-white p-3 shadow rounded">
        {% include "blog/snippets/main_post_list.html" %}
      </div>
      <div class="pagination-section mt-4">
        {% include "blog/snippets/pagination.html" %}
      </div>
    </main>
    <aside class="col-lg-4">
      <div class="sidebar-section bg-white p-3 shadow rounded">
        {% include "blog/snippets/sidebar.html" %}
      </div>
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block title %}Comment Submission Form{{ block.super }}{% endblock %}
{% block description %}Comment Submission Form{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">Comment Submission Form</h1>
      <p>To:<{{ post.title }}></p>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block title %}All Posts | {{ block.super }}{% endblock %}
{% block description %}The Road to AI Species{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4 text-uppercase font-weight-bold border-bottom pb-2">List of posts</h1>
      <div class="main-posts bg-white p-3 shadow rounded">
        {% include "blog/snippets/main_post_list.html" %}
      </div>
      <div class="pagination-section mt-4">
        {% include "blog/snippets/pagination.html" %}
        {# {% include "blog/snippets/pagination_b.html" %} #}
      </div>
    </main>
    <aside class="col-lg-4">
      <div class="sidebar-section bg-white p-3 shadow rounded">
        {% include "blog/snippets/sidebar.html" %}
      </div>
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }} | {{ block.super }}{% endblock %}
{% block description %}{{ object.description }}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <article class="blog-post shadow p-3 mb-5 bg-white rounded">
        <h1 class="text-uppercase font-weight-bold">{{ object.title }}</h1>
        <div class="d-flex justify-content-between">
          <p><small>{{ object.published_at|date:"Y-m-d H:i:s" }}</small></p>
          <p class="text-muted">{{ object.category.name }}</p>
        </div>
        <div class="tags">
          {% for tag in object.tags.all %}
          <span class="badge badge-secondary">{{ tag.name }}</span>
          {% endfor %}
        </div>
        <hr>
        <div class="content-body">{{ object.content|safe }}</div>
      </article>
      <article class="comment-section mt-5">
        <h4 class="mb-4">comment</h4>
        <a class="btn btn-primary mb-3" href="{% url 'blog:comment_form' post.pk %}">Post a comment</a>
        {% include "blog/snippets/comments.html" %}
      </article>
    </main>
    <aside class="col-md-4">
      <div class="sidebar-section shadow p-3 mb-5 bg-white rounded">
        {% include "blog/snippets/sidebar.html" %}
      </div>
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Profile Page</h1>
    <section>
        <h2>About Me</h2>
	{% load static %}
	<div class="col-md-6">
		<img src="https://bankofai.link/ceo-image1.jpg" alt="Profile Image 1" class="img-fluid">
	</div>
        <p>I am a seasoned software engineer with extensive expertise in web development, Artificial Intelligence (AI),
            and data analysis. Driven by a strong sense of curiosity and innovation, I have dedicated myself to creating
            intelligent solutions that are tailored to global needs.</p>

        <h3>Skills</h3>
        <ul>
            <li><strong>Software Development:</strong> Designing and developing robust software systems tailored to
                clients' needs.
            </li>
            <li><strong>Web Development:</strong> Crafting interactive and responsive websites using cutting-edge
                technologies.
            </li>
            <li><strong>Artificial Intelligence:</strong> Implementing machine learning algorithms and AI-based
                solutions.
            </li>
            <li><strong>Data Analysis:</strong> Utilizing statistical techniques and data visualization tools to
                interpret complex data, providing actionable insights.
            </li>
        </ul>

        <h3>Contact</h3>
        <ul>
            <li><a href="https://www.linkedin.com/in/kensuke-nagoya-b2585a190/" target="_blank">LinkedIn</a></li>
            <li><a href="https://bankofai.link/" target="_blank">Website</a></li>
            <li><a href="https://github.com/NagoyaKensuke" target="_blank">GitHub</a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100038580636167" target="_blank">Facebook</a></li>
            <li><a href="https://twitter.com/agi_ken" target="_blank">Twitter</a></li>
            <li><a href="https://www.instagram.com/agi_nagoya/" target="_blank">Instagram</a></li>
            <li><a href="https://www.google.co.jp/maps/contrib/104016231476718989361" target="_blank">Google Maps Local
                Guides</a></li>
        </ul>
        <div class="row">
            {% for i in "1234567890ab"|make_list %}
            <div class="col-md-6">
                <img src="https://bankofai.link/profile{{ i }}.jpg" alt="Profile Image {{ i }}" class="img-fluid mb-4">
            </div>
            {% endfor %}
        </div>
    </section>

</div>
{% endblock %}

blog/templates/blog/reply_form.html
{% extends "base.html" %}

{% block title %}Comment Reply Form | {{ block.super }}{% endblock %}
{% block description %}Comment Reply Form{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">Comment Reply Form</h1>
      <p>To: {{ comment.author }}</p>
      <p class="text-black-50">{{ comment.text|linebreaksbr }}</p>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">submit</button>
      </form>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/search_post.html
{% extends "base.html" %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block description %}Search Word<{% if query %}{{ query }}{% endif %}>{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">Result of <{% if query %}{{ query }}{% endif %}></h1>
      <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}cases {{ paginator.count }}cases</p>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
      {# {% include "blog/snippets/pagination_b.html" %} #}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/tag_list.html
{% extends "base.html" %}

{% block title %}All Tags List | {{ block.super }}{% endblock %}
{% block description %}All Tag List{% endblock %}

{% block content %}
<h1>All Tag List</h1>
<ul>
  {% for tags in object_list %}
  <li><a href="{% url 'blog:tag_post' tag.slug %}">{{ tag.name }} ({{ tag.num_posts }})</a></li>
  {% empty %}
  <li>No Tags</li>
  {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/tag_post.html
{% extends "base.html" %}

{% block title %}#{{ tag.name }} | {{ block.super }}{% endblock %}
{% block description %}This is the list page of {{ tag.name }} posts.{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4 text-uppercase font-weight-bold border-bottom pb-2">Tag: {{ tag.name }}</h1>
      <div class="main-posts bg-white p-3 shadow rounded">
        {% include "blog/snippets/main_post_list.html" %}
      </div>
      <div class="pagination-section mt-4">
        {% include "blog/snippets/pagination.html" %}
      </div>
    </main>
    <aside class="col-lg-4">
      <div class="sidebar-section bg-white p-3 shadow rounded">
        {% include "blog/snippets/sidebar.html" %}
      </div>
    </aside>
  </div>
</div>
{% endblock %}